baseurl = "http://blayhem.github.io/"
languageCode = "en-us"
title = "dfr"

theme = "cactus"
description = ""

[Params]
  name = "Daniel Fernandez"
  bio = "CS student, jr developer, passionate learner"
  AuthorName = "dfr"
  github = "blayhem"
  description = "Hugo testing"
  email = ""
  twitter = "blayhem"
  enableRSS = true

  # Navigation links
	home = ""
	about = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""

	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

    # Social icons style - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/"
    facebook = "https://www.facebook.com/"
    github   = "https://www.github.com/"
    dribble  = "https://www.dribbble.com/"